version: 2.0.1.{build}
image:
- Visual Studio 2017
platform:
- x64
environment:
  matrix:
  - PYTHON: "C:\Python36-x64"
install:
- SET PATH=%PYTHON%;%PYTHON%\Scripts\;%PATH%
- python --version
- python -m pip install --upgrade pip wheel
- python -m pip install pytest numpy --no-warn-script-location
- mkdir build_64
- cd build_64
- cmake -DBUILD_TESTS=on -DBUILD_PYTHONEXT=on -A x64 ..
build_script:
- cmake --build . -- -j2
test_script:
- ctest -V
