notifications:
  email: false
  slack:
    secure: ilztqDylzgDwnh+AAHdrmHjgD4rjutJa5rh783H8HfW7KKY+RtHaAa+Z9V6uAbU3/fPk29fkCXRxT/scAI4Fn0TQ/Hi0alCs7ytNJg+2fbVcI5xWHbmJznOb0pQl0Gn6MGwouSyP9WvRtivtT5u+wlNR6yKycTmUI9qP3Fe7nA/k/WdRt5SHGjjprtYZYbBOg+9UStzubMuQj5hTBeDs78UyUbejSsZ0Cp9+OkTcugoEegwn0o9QdkvFGHF/hQ5bVGGNVAFUVOg+B4DFiw59MbsgIDZ663CXCTxUJ1I4uS3rI7LpnY2G8c5dKp9E2KDkM8sPKWzg4qeyj1POMPNDUbNYWIHBBK4NxrQ+PqW1nquxNTVsqYi2IXVmV2BWx9+SUS06YwDsjrCcQyAtnCzxn/tL3aX/8jyeN3yPwytJgDuj9IF8nIJZuuMgDOs1ZVa9fbL8ANBMcZMKIPCSwjO8670ULl5xKAWKGTY7HwzGLU3syQBwOX+eukf9zx2Y9qrsP1kJJT8YTOD45icJRAMPQQEiN20wxKh/V7Kz0ewc6LG8Bv1FyM6f+7ehNZvkwrStzJJ85JwDkPeTKKiBa3kuBQzE0CBm3/cTYCXgQEo3jggH1xPF8OkbYhuX8TrZjp3PBVCABto6V6OGILFA7Hhv6gK9eHxCSVOICPfWCfYXakY=
language: cpp
dist: xenial
sudo: false
git:
  depth: false
branches:
  only:
  - master
  - development
  - pybind11
matrix:
  fast_finish: true
  allow_failures:
  - os: windows
  include:
  - os: osx
    osx_image: xcode
    before_install:
    - brew upgrade cmake
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
    - pyenv global 3.7.1
  - os: windows
    env:
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - MATRIX_EVAL="CC=CL.exe && CXX=CL.exe"
    before_install:
    - choco install python
before_install:
- eval "${MATRIX_EVAL}"
- "${CXX} --version"
install:
- mkdir build; cd build;
- |
  # Configure
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cmake -DGETEIGEN=on -DGAMER_TEST=on -DBUILD_PYGAMER=on -A x64 ..
    cmake --build .
  else
    cmake -DGETEIGEN=on -DGAMER_TEST=on -DBUILD_PYGAMER=on ..
    cmake --build . -- -j2
  fi
script:
- ctest -V